pre_bump_hooks = [
    """
        bash -c "if ! ./gradlew test --info; then exit 1; fi"
    """,
    "echo 'Bumping from v{{latest}} to v{{version}}!'",
]
post_bump_hooks = [
    # Update the version in gradle properties and amend last commit
    "sed -i 's/version=.*/version=v{{version}}/' ./gradle.properties",
    "git add ./gradle.properties",
    "git commit --amend -C HEAD",
    # Push to github with new tag
    "git push",
    "git push origin v{{version}}",
    # Trigger the docs workflow
    "gh workflow run docs.yml",
    # Publish to repo
    "./gradlew clean publish -Pversion=\"v{{version}}\"",
    # Update tags
    "git fetch --tags origin",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Elixir"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]