pre_bump_hooks = [
    "nu -c \"cog-scripts/src/pre-bump.nu {{latest}} {{version}}\"",
]
post_bump_hooks = [
    "nu -c \"cog-scripts/src/post-bump.nu Elixir -r -p Elixir-API -p Elixir-Core {{latest}} {{version}} {{version+patch-SNAPSHOT}}\"",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Elixir"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]